### ISSUE TITLE
Pantalla de registro/login

### ISSUE THREAD

**Issue by Virako** [wadobo/socializa-ios#1]
![login](https://user-images.githubusercontent.com/815686/50953682-715b7a00-14b4-11e9-980c-ae5b27777368.png)

Necesitamos una pantalla de login similar a la anterior. Los botones serían los de facebook y google, los cuales tienen que hacer una llamada con el token recibido de dichas redes sociales a backend para recibir un access_token válido para nuestra api:

Lllamada POST:  BASE/api/v1.0/auth/convert-token/

Parámetros:
```
{
  "client_id": CLIENT_ID,
  "grant_type": "convert_token",
  "backend" : "facebook",
  "token": TOKEN_RECIBIDO
}
```

Respuesta:
```
{
  "access_token": ACCESS_TOKEN,
  "token_type": TOKEN_TYPE,
  "refresh_token": REFRESH_TOKEN
}
```

Con esta respuesta ya tenemos nuestro token para poder acceder a la API, el cual tendremos que meterlo en el header de la llamada, de la siguiente manera:

`{ "Authorization": "\(TOKEN_TYPE) \(ACCESS_TOKEN)"}
`

Algunos detalles a tener en cuenta:
* De facebook necesitamos que se haga la llamada con los permisos para obtener el email, en caso de que no nos lo den, no dejar que se registren/logeen y mostrar un mensaje de que el email es necesario para guardar sus progresos.
* El token_type y el access_token que obtenemos, tenemos que guardarlo para poder realizar peticiones a la api a futuro y no tener que logearnos cada vez que entremos en la app.
* Una vez logeados o si entramos en la app y ya nos hemos logeado previamente, nos iremos directamente a la pantalla principal (se definirá en otra issue diferente)

Recursos: [logo](https://user-images.githubusercontent.com/815686/50953726-951ec000-14b4-11e9-87a9-be133a1307d2.png)

**Comment by jmayoralas** [comment]
Para empezar, necesitaría acceso a los recursos gráficos. Veo que el logo sí me lo has dado, pero ¿los botones los puedo pillar de algún sitio?

Edito:
Vale veo que me dices que los botones los pille de facebook y google. Ok !

**Comment by jmayoralas** [comment]
Hecho !

A falta de ver por qué el backend está poniendo facebook como APPLICATION incluso cuando el login se hace desde Google.
